NEO4J_URI = "bolt:"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = ""
#星火认知大模型Spark Max的URL值，其他版本大模型URL值请前往文档（https://www.xfyun.cn/doc/spark/Web.html）查看
SPARKAI_URL = "wss://spark-api.xf-yun.com/{version}/chat"
#星火认知大模型调用秘钥信息，请前往讯飞开放平台控制台（https://console.xfyun.cn/services/bm35）查看
SPARKAI_APP_ID = ""
SPARKAI_API_KEY = ""
SPARKAI_API_SECRET = ""
#星火认知大模型Spark Max的domain值，其他版本大模型domain值请前往文档（https://www.xfyun.cn/doc/spark/Web.html）查看
SPARKAI_DOMAIN = "Your application domain"

# mv secrests_example.toml secrets.toml